[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[[bin]]
doc = false
name = "lrpar"

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2.1"
regex = "0.1.8"
