[package]
name = "lrtable"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[lib]
name = "lrtable"
path = "src/lib/mod.rs"

[dependencies]
bit-vec = "0.4.3"
getopts = "0.2.14"
regex = "0.1.65"
