[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[dependencies]
bit-vec = "0.4.1"
getopts = "0.2.1"
regex = "0.1.8"
