[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[[bin]]
doc = false
name = "lrpar"

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[dependencies]
cactus = "1.0.2"
cfgrammar = { git = "https://github.com/softdevteam/cfgrammar" }
getopts = "0.2.17"
indexmap = "0.4.1"
lrlex = { git = "http://github.com/softdevteam/lrlex" }
lrtable = { git = "http://github.com/softdevteam/lrtable" }
num-traits = "0.2.1"
vob = "1.0.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
