[package]
name = "lrtable"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[lib]
name = "lrtable"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2.15"
fnv = "1.0.5"
macro-attr = "0.2.0"
newtype_derive = "0.1.6"
cfgrammar = { git = "https://github.com/softdevteam/cfgrammar" }
vob = "0.1.0"
