[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[[bin]]
doc = false
name = "lrpar"

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2.14"
cactus = "0.1.0"
cfgrammar = { git = "https://github.com/softdevteam/cfgrammar" }
lrtable = { git = "http://github.com/softdevteam/lrtable" }
lrlex = { git = "http://github.com/softdevteam/lrlex" }
