[workspace]
members=[
    "cfgrammar",
    "lrlex",
    "lrlex/examples/calclex",
    "lrpar",
    "lrpar/examples/calcparse",
    "lrpar/examples/actions",
    "lrtable",
    "nimbleparse"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
