[package]
name = "cfgrammar"
description = "Grammar manipulation"
repository = "https://github.com/softdevteam/grmtools"
version = "0.2.1"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
readme = "README.md"
# This should be "Apache-2.0 OR MIT OR UPL-1.0" but crates.io doesn't know about
# UPL-1.0.
license = "Apache-2.0 OR MIT"
categories = ["parsing"]
keywords = ["yacc", "grammar"]

[lib]
name = "cfgrammar"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2"
lazy_static = "1.0"
indexmap = "1.0"
num-traits = "0.2"
regex = "1.0"
serde = { version="1.0", features=["derive"], optional=true }
vob = { version="2.0", features=["serde"] }
