[package]
name = "lrtable"
description = "LR grammar table generation"
repository = "https://github.com/softdevteam/grmtools"
version = "0.4.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
readme = "README.md"
# This should be "Apache-2.0 OR MIT OR UPL-1.0" but crates.io doesn't know about
# UPL-1.0.
license = "Apache-2.0 OR MIT"
categories = ["parsing"]

[lib]
name = "lrtable"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2"
fnv = "1.0"
macro-attr = "0.2.0"
newtype_derive = "0.1.6"
num-traits = "0.2"
cfgrammar = { path="../cfgrammar", version = "0.4", features=["serde"] }
serde = { version="1.0", features=["derive"], optional=true }
vob = { version="2.0", features=["serde"] }
sparsevec = { version="0.1", features=["serde"] }
static_assertions = "0.3"
try_from = "0.3"
