[package]
name = "nimbleparse"
version = "0.6.2"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
license = "Apache-2.0/MIT"

[[bin]]
doc = false
name = "nimbleparse"

[dependencies]
cfgrammar = { path="../cfgrammar" }
getopts = "0.2"
lrlex = { path="../lrlex" }
lrpar = { path="../lrpar" }
lrtable = { path="../lrtable" }
num-traits = "0.2"
