[package]
name = "calclex"
version = "0.1.0"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]

[[bin]]
doc = false
name = "calclex"

[build-dependencies]
lrlex = { path = "../.." }

[dependencies]
lrlex = { path = "../.." }
lrpar = { path = "../../../lrpar" }
