[package]
name = "lrpar"
description = "Yacc-compatible parser generator"
repository = "https://github.com/softdevteam/grmtools"
version = "0.4.2"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
readme = "README.md"
# This should be "Apache-2.0 OR MIT OR UPL-1.0" but crates.io doesn't know about
# UPL-1.0.
license = "Apache-2.0 OR MIT"
build = "build.rs"
categories = ["parsing"]
keywords = ["parser", "LR", "yacc", "grammar"]

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[build-dependencies]
vergen = "2"

[dependencies]
bincode = "1.0"
cactus = "1.0"
cfgrammar = { path="../cfgrammar", version = "0.4", features=["serde"] }
filetime = "0.2"
getopts = "0.2"
indexmap = "1.0"
lazy_static = "1.2"
lrtable = { path="../lrtable", version = "0.4", features=["serde"] }
num-traits = "0.2"
packedvec = "1.0"
rmp-serde = "0.13"
serde = { version="1.0", features=["derive"] }
static_assertions = "0.3"
typename = "0.1"
vob = "2.0"
regex = "1.0"

[dev-dependencies]
tempfile = "3.0"
glob = "0.2"
yaml-rust = "0.4"
