[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]

[[bin]]
doc = false
name = "lrpar"

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[dependencies]
cactus = "1.0"
cfgrammar = { path="../cfgrammar", features=["serde"] }
getopts = "0.2"
indexmap = "1.0"
lrlex = { path="../lrlex" }
lrtable = { path="../lrtable", features=["serde"] }
num-traits = "0.2"
rmp-serde = "0.13"
serde = { version="1.0", features=["derive"] }
typename = "0.1"
vob = "1.3"
