[package]
name = "lrpar"
version = "0.1.0"
authors = ["Lukas Diekmann <http://lukasdiekmann.com/>", "Laurence Tratt <http://tratt.net/laurie/>"]
build = "build.rs"

[lib]
name = "lrpar"
path = "src/lib/mod.rs"

[build-dependencies]
vergen = "2"

[dependencies]
bincode = "1.0"
cactus = "1.0"
cfgrammar = { path="../cfgrammar", features=["serde"] }
filetime = "0.2"
getopts = "0.2"
indexmap = "1.0"
lrtable = { path="../lrtable", features=["serde"] }
num-traits = "0.2"
rmp-serde = "0.13"
serde = { version="1.0", features=["derive"] }
typename = "0.1"
vob = "1.3"

[dev-dependencies]
regex = "1.0"
