[package]
name = "lrlex"
description = "Simple lexer generator"
repository = "https://github.com/softdevteam/grmtools"
version = "0.4.2"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["parsing"]

[[bin]]
doc = false
name = "lrlex"

[lib]
name = "lrlex"
path = "src/lib/mod.rs"

[dependencies]
getopts = "0.2.15" # only needed for src/main.rs
lazy_static = "1.2"
lrpar = { path = "../lrpar", version = "0.4" }
regex = "1.0"
num-traits = "0.2"
try_from = "0.3"
typename = "0.1"
